require 'faker'
require 'active_support/core_ext/string/output_safety'
require 'active_support/concern'
require 'action_view/helpers/capture_helper'
require 'action_view/helpers/tag_helper'
require 'fakerama/content'
